title: Adeline Chacon | Data Analyst
description: Portfolio of data analysis, visualization, and problem-solving projects.
theme: jekyll-theme-minimal

github_username: AMargaillan
linkedin: www.linkedin.com/in/adeline-chacon-13b266173

# Navigation links
nav:
  - name: Home
    link: /
  - name: Projects
    link: /projects
  - name: About
    link: /#about


